default_language_version:
    python: python3.12
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pycqa/pylint
    rev: v4.0.5
    hooks:
      - id: pylint
        additional_dependencies:
        - aiohttp==3.7.3
        - netifaces==0.11.0
        - urllib3==1.26.3
        - tenacity==8.2.3
        exclude: 'tests/'
        args:
        - --ignore=setup.py
        - --extension-pkg-allow-list=netifaces
